Matrix()
Matrix( std::initializer_list<Vector<T,N>> )
Matrix( const Matrix<T,M,N> & )
at( size_t )
at( size_t, size_t )
Vector<T,N> Matrix<T,M,N>::operator[]( size_t i ) const
Vector<T,N> & Matrix<T,M,N>::operator[]( size_t i )
Vector<T,N> & Matrix<T,M,N>::operator[]( size_t i )
Matrix<T,M,N> inverse( const Matrix<T,M,N> & )
bool isnan( const Matrix<T,M,N> & )
bool operator==( const Matrix<T,M,N> &, const Matrix<T,M,N> & )
bool operator!=( const Matrix<T,M,N> &, const Matrix<T,M,N> & )
std::ostream & operator<<( std::ostream, const Matrix<T,M,N> & )
Matrix<T,M,N> operator+( const Matrix<T,M,N> &, const Matrix<T,M,N> & )
Matrix<T,M,N> operator-( const Matrix<T,M,N> & )
Matrix<T,M,N> operator-( const Matrix<T,M,N> &, const Matrix<T,M,N> & )
Matrix<T,M,N> operator*( const T &, const Matrix<T,M,N> & )
Matrix<T,M,N> operator*( const Matrix<T,M,N> &, const T & )
Vector<T,M> operator*( const Matrix<T,M,N> &, const Vector<T,N> & )
Matrix<T,M,O> operator*( const Matrix<T,M,N> &, const Matrix<T,N,O> & )
Matrix<T,M,N> operator/( const Matrix<T,M,N> & m, const T & s )
Matrix<T,M,N> to_string( const Matrix<T,M,N> & )
Matrix<T,M,N> transpose( const Matrix<T,M,N> & )